name: Deploy Preview Environment

on:
  push:
    branches:
      - preview

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy Preview to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: AkaiMPCChordProgressionGeneratorPreview
          target-folder: AkaiMPCChordProgressionGeneratorPreview
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
